import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#904b46",
        "inverse-surface": "#2d312f",
        "inverse-on-surface": "#eff1ed",
        "primary-container": "#1e6b52",
        "secondary-container": "#b4ecd3",
        "secondary-fixed-dim": "#9cd2ba",
        primary: "#00523c",
        "surface-container-high": "#e6e9e5",
        "on-tertiary-fixed": "#3a0908",
        "on-surface": "#181c1a",
        "on-secondary-fixed": "#002116",
        tertiary: "#733430",
        background: "#f7faf6",
        "primary-fixed-dim": "#8cd5b7",
        "surface-dim": "#d8dbd7",
        "surface-container-highest": "#e0e3df",
        outline: "#6f7974",
        "surface-tint": "#1d6a51",
        "inverse-primary": "#8cd5b7",
        "on-primary-container": "#9ee9c9",
        "on-primary-fixed": "#002116",
        "on-tertiary-fixed-variant": "#723430",
        "on-background": "#181c1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#1a503d",
        "on-tertiary-container": "#ffcec9",
        "surface-variant": "#e0e3df",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#00513b",
        "outline-variant": "#bfc9c2",
        secondary: "#346854",
        "surface-container-low": "#f1f4f0",
        "primary-fixed": "#a7f2d2",
        "on-primary": "#ffffff",
        "secondary-fixed": "#b7eed5",
        surface: "#f7faf6",
        "on-surface-variant": "#3f4944",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container": "#ecefeb",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-bright": "#f7faf6",
        "on-secondary-container": "#386c58",
        "surface-container-lowest": "#ffffff",
        // Navigator / UAB specific
        "uab-gold": "#FFD602",
        "uab-green": "#1E6B52",
        "uab-deep-green": "#144B39",
        "map-bg": "#F8F9FA",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        md: "24px",
        sm: "12px",
        xl: "64px",
        xs: "4px",
        lg: "40px",
        margin: "32px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "screen-xl": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
